name: Development Build

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-development:
    name: Build Development
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.18
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Run tests
        run: bun test
      
      - name: Build development
        run: eas build --platform all --profile development --non-interactive
        env:
          EAS_BUILD_NUMBER: ${{ github.run_number }}
      
      - name: Comment PR with build info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Development build completed! Check your Expo dashboard for the build.'
            })
